name: 'build'
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21'

      - name: Build
        run: |
          sudo apt-get install gcc libgl1-mesa-dev xorg-dev
          go mod download
          go build .
